# Generated by Django 2.1.4 on 2018-12-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='name',
            new_name='names',
        ),
    ]
