# Generated by Django 2.1.4 on 2018-12-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0002_auto_20181206_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='names',
            new_name='name',
        ),
    ]
