# Generated by Django 2.1.4 on 2018-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0003_auto_20181206_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(to='djangotwitter.Author'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
