# Generated by Django 2.1.4 on 2018-12-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0004_auto_20181206_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(default='poo', to='djangotwitter.Author'),
        ),
    ]
