# Generated by Django 2.1.4 on 2018-12-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0005_auto_20181206_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, to='djangotwitter.Author'),
        ),
    ]
