# Generated by Django 2.1.4 on 2018-12-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangotwitter', '0005_auto_20181209_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='metioned_by',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
    ]
